const SUPABASE_URL = 'https://owavyvaparyftjxwcocr.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93YXZ5dmFwYXJ5ZnRqeHdjb2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2MzQ3NTIsImV4cCI6MjA5MjIxMDc1Mn0._c2i5hFpBa03yggCJGOsEJvtnnCBZD-AxOOJWJrNnVg';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
